export default {
    products: [
      {
        _id: '1',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: '/images/BB.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4.3,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: '/images/elara-double-drawer-bedside-table-lifestyle-rectangle.jpg',
        price: 70,
        brand: 'Wakefit',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: '/images/GD.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: '/images/LEAFY.jpg',
        price: 90,
        brand: 'Wakefit',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: '/images/TN.jpg',
        price: 119,
        brand: 'Wakefit',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: '/images/BB.jpg',
        price: 85,
        brand: 'Wakefit',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      },   {
        _id: '1',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: '/images/BB.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: '/images/elara-double-drawer-bedside-table-lifestyle-rectangle.jpg',
        price: 70,
        brand: 'Wakefit',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: '/images/GD.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: '/images/LEAFY.jpg',
        price: 90,
        brand: 'Wakefit',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: '/images/TN.jpg',
        price: 119,
        brand: 'Wakefit',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: '/images/BB.jpg',
        price: 85,
        brand: 'Wakefit',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      },   {
        _id: '1',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: '/images/BB.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: '/images/elara-double-drawer-bedside-table-lifestyle-rectangle.jpg',
        price: 70,
        brand: 'Wakefit',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: '/images/GD.jpg',
        price: 59,
        brand: 'Wakefit',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: '/images/LEAFY.jpg',
        price: 90,
        brand: 'Wakefit',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: '/images/TN.jpg',
        price: 119,
        brand: 'Wakefit',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: '/images/BB.jpg',
        price: 85,
        brand: 'Wakefit',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      }
    ],
  };